from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='SiteProfile', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),
            ('full_name', models.CharField(default='Elmira Behrouzi', max_length=160)),
            ('role_en', models.CharField(default='Software Developer', max_length=180)),('role_fa', models.CharField(blank=True, default='توسعه‌دهنده نرم‌افزار', max_length=180)),('role_de', models.CharField(blank=True, default='Softwareentwicklerin', max_length=180)),
            ('hero_en', models.TextField(blank=True, default='Building practical digital products with code, clarity, and curiosity.')),('hero_fa', models.TextField(blank=True, default='ساخت محصولات دیجیتال کاربردی با کد، دقت و کنجکاوی.')),('hero_de', models.TextField(blank=True, default='Praktische digitale Produkte mit Code, Klarheit und Neugier entwickeln.')),
            ('bio_en', models.TextField(blank=True)),('bio_fa', models.TextField(blank=True)),('bio_de', models.TextField(blank=True)),
            ('email', models.EmailField(default='behroozielmira1234@gmail.com', max_length=254)),('phone', models.CharField(default='09903599296', max_length=50)),
            ('location_en', models.CharField(blank=True, default='Iran', max_length=160)),('location_fa', models.CharField(blank=True, default='ایران', max_length=160)),('location_de', models.CharField(blank=True, default='Iran', max_length=160)),
            ('github_url', models.URLField(blank=True)),('linkedin_url', models.URLField(blank=True)),('behance_url', models.URLField(blank=True)),('instagram_url', models.URLField(blank=True)),
            ('resume_en_url', models.URLField(blank=True)),('resume_fa_url', models.URLField(blank=True)),('resume_de_url', models.URLField(blank=True)),('avatar_url', models.URLField(blank=True)),
            ('available_remote', models.BooleanField(default=True)),('available_freelance', models.BooleanField(default=True)),('available_full_time', models.BooleanField(default=True)),
        ]),
        migrations.CreateModel(name='Project', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),
            ('title_en', models.CharField(max_length=180)),('title_fa', models.CharField(blank=True, max_length=180)),('title_de', models.CharField(blank=True, max_length=180)),('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ('short_en', models.TextField(blank=True)),('short_fa', models.TextField(blank=True)),('short_de', models.TextField(blank=True)),('description_en', models.TextField(blank=True)),('description_fa', models.TextField(blank=True)),('description_de', models.TextField(blank=True)),
            ('problem_en', models.TextField(blank=True)),('problem_fa', models.TextField(blank=True)),('problem_de', models.TextField(blank=True)),('solution_en', models.TextField(blank=True)),('solution_fa', models.TextField(blank=True)),('solution_de', models.TextField(blank=True)),('challenges_en', models.TextField(blank=True)),('challenges_fa', models.TextField(blank=True)),('challenges_de', models.TextField(blank=True)),
            ('category', models.CharField(choices=[('backend','Backend'),('fullstack','Full Stack'),('api','API'),('automation','Automation'),('data','Data'),('frontend','Frontend'),('other','Other')], default='backend', max_length=30)),('tech_stack', models.JSONField(blank=True, default=list)),('features', models.JSONField(blank=True, default=list)),
            ('cover_url', models.URLField(blank=True)),('github_url', models.URLField(blank=True)),('live_url', models.URLField(blank=True)),('role', models.CharField(blank=True, max_length=180)),('duration', models.CharField(blank=True, max_length=100)),('project_type', models.CharField(blank=True, max_length=100)),('featured', models.BooleanField(default=False)),('published', models.BooleanField(default=True)),('order', models.PositiveIntegerField(default=0)),
        ], options={'ordering':['order','-created_at']}),
        migrations.CreateModel(name='Skill', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=120)),('category', models.CharField(choices=[('programming','Programming'),('backend','Backend'),('frontend','Frontend'),('database','Database'),('tools','Tools'),('design','Design'),('professional','Professional')], max_length=30)),('level', models.PositiveSmallIntegerField(default=70)),('icon', models.CharField(blank=True, max_length=80)),('currently_learning', models.BooleanField(default=False)),('order', models.PositiveIntegerField(default=0)),
        ], options={'ordering':['category','order','name']}),
        migrations.CreateModel(name='Experience', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('role_en', models.CharField(max_length=180)),('role_fa', models.CharField(blank=True, max_length=180)),('role_de', models.CharField(blank=True, max_length=180)),('company', models.CharField(blank=True, max_length=180)),('start_label', models.CharField(blank=True, max_length=60)),('end_label', models.CharField(blank=True, max_length=60)),('description_en', models.TextField(blank=True)),('description_fa', models.TextField(blank=True)),('description_de', models.TextField(blank=True)),('bullets', models.JSONField(blank=True, default=list)),('order', models.PositiveIntegerField(default=0)),('published', models.BooleanField(default=True)),
        ], options={'ordering':['order','-created_at']}),
        migrations.CreateModel(name='Education', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('title_en', models.CharField(max_length=180)),('title_fa', models.CharField(blank=True, max_length=180)),('title_de', models.CharField(blank=True, max_length=180)),('institution', models.CharField(blank=True, max_length=180)),('year_label', models.CharField(blank=True, max_length=80)),('description_en', models.TextField(blank=True)),('description_fa', models.TextField(blank=True)),('description_de', models.TextField(blank=True)),('order', models.PositiveIntegerField(default=0)),('published', models.BooleanField(default=True)),
        ], options={'ordering':['order','-created_at']}),
        migrations.CreateModel(name='DesignProject', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('title_en', models.CharField(max_length=180)),('title_fa', models.CharField(blank=True, max_length=180)),('title_de', models.CharField(blank=True, max_length=180)),('slug', models.SlugField(blank=True, max_length=200, unique=True)),('short_en', models.TextField(blank=True)),('short_fa', models.TextField(blank=True)),('short_de', models.TextField(blank=True)),('tools', models.JSONField(blank=True, default=list)),('cover_url', models.URLField(blank=True)),('case_study_url', models.URLField(blank=True)),('real_project', models.BooleanField(default=True)),('published', models.BooleanField(default=True)),('order', models.PositiveIntegerField(default=0)),
        ], options={'ordering':['order','-created_at']}),
        migrations.CreateModel(name='BlogPost', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('title_en', models.CharField(max_length=220)),('title_fa', models.CharField(blank=True, max_length=220)),('title_de', models.CharField(blank=True, max_length=220)),('slug', models.SlugField(blank=True, max_length=240, unique=True)),('excerpt_en', models.TextField(blank=True)),('excerpt_fa', models.TextField(blank=True)),('excerpt_de', models.TextField(blank=True)),('body_en', models.TextField(blank=True)),('body_fa', models.TextField(blank=True)),('body_de', models.TextField(blank=True)),('tags', models.JSONField(blank=True, default=list)),('cover_url', models.URLField(blank=True)),('published', models.BooleanField(default=False)),('published_at', models.DateTimeField(blank=True, null=True)),
        ], options={'ordering':['-published_at','-created_at']}),
        migrations.CreateModel(name='ContactMessage', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('name', models.CharField(max_length=160)),('email', models.EmailField(max_length=254)),('subject', models.CharField(blank=True, max_length=220)),('message', models.TextField()),('status', models.CharField(choices=[('unread','Unread'),('read','Read'),('replied','Replied'),('archived','Archived')], default='unread', max_length=20)),('ip_address', models.GenericIPAddressField(blank=True, null=True)),('user_agent', models.TextField(blank=True)),
        ], options={'ordering':['-created_at']}),
    ]
