import React,{useEffect,useMemo,useState} from 'react'
import {Plus,Trash2,Pencil,Save,X,RefreshCw} from 'lucide-react'
import api,{unwrap} from '../../api'
import UploadInput from '../../components/UploadInput'
import AdminLayout from './AdminLayout'

const isArrayField=f=>f.type==='array'
const normalizeForEdit=(item,schema)=>{const out={};schema.forEach(f=>{let v=item?.[f.name];if(isArrayField(f))v=Array.isArray(v)?v.join(', '):(v||'');if(f.type==='checkbox')v=Boolean(v);out[f.name]=v??''});return out}
const serialize=(form,schema)=>{const out={...form};schema.forEach(f=>{if(isArrayField(f))out[f.name]=(form[f.name]||'').split(',').map(x=>x.trim()).filter(Boolean);if(f.type==='number')out[f.name]=Number(form[f.name]||0)});return out}
export default function EntityManager({title,eyebrow,endpoint,schema,columns,lookup='id',description}){
 const [items,setItems]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(normalizeForEdit({},schema)),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=()=>api.get(endpoint).then(r=>setItems(unwrap(r.data))).catch(()=>setError('Could not load data.'))
 useEffect(()=>{load()},[endpoint])
 const startNew=()=>{setEditing('new');setForm(normalizeForEdit({},schema));setError('')}
 const startEdit=item=>{setEditing(item);setForm(normalizeForEdit(item,schema));setError('')}
 const cancel=()=>{setEditing(null);setForm(normalizeForEdit({},schema))}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');const payload=serialize(form,schema);try{if(editing==='new')await api.post(endpoint,payload);else await api.patch(`${endpoint}${editing[lookup]}/`,payload);await load();cancel()}catch(err){setError(JSON.stringify(err.response?.data||'Could not save.'))}finally{setBusy(false)}}
 const remove=async item=>{if(!confirm(`Delete ${item[columns[0]?.field]||'this item'}?`))return;try{await api.delete(`${endpoint}${item[lookup]}/`);load()}catch{setError('Could not delete item.')}}
 return <AdminLayout><div className="admin-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="admin-title-actions"><button className="btn" onClick={load}><RefreshCw size={15}/></button><button className="btn primary" onClick={startNew}><Plus size={16}/> Add new</button></div></div>{error&&<div className="admin-error">{error}</div>}<div className="manager-layout"><section className="admin-panel table-panel"><div className="table-wrap"><table className="admin-table"><thead><tr>{columns.map(c=><th key={c.field}>{c.label}</th>)}<th/></tr></thead><tbody>{items.map(item=><tr key={item.id}>{columns.map(c=><td key={c.field}>{c.render?c.render(item[c.field],item):String(item[c.field]??'—')}</td>)}<td className="row-actions"><button onClick={()=>startEdit(item)}><Pencil size={15}/></button><button className="danger" onClick={()=>remove(item)}><Trash2 size={15}/></button></td></tr>)}{!items.length&&<tr><td colSpan={columns.length+1}><div className="table-empty">No items yet.</div></td></tr>}</tbody></table></div></section>{editing&&<section className="editor-panel"><div className="panel-head"><div><small>{editing==='new'?'NEW ITEM':'EDIT ITEM'}</small><h2>{editing==='new'?'Create':editing[columns[0]?.field]}</h2></div><button className="icon-btn" onClick={cancel}><X/></button></div><form className="admin-form" onSubmit={save}>{schema.map(f=><Field key={f.name} f={f} value={form[f.name]} setValue={v=>setForm({...form,[f.name]:v})}/>)}<div className="form-actions"><button type="button" className="btn" onClick={cancel}>Cancel</button><button className="btn primary" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save'}</button></div></form></section>}</div></AdminLayout>
}
function Field({f,value,setValue}){if(f.type==='upload')return <label><span>{f.label}</span><UploadInput value={value} onChange={setValue} accept={f.accept||'image/*,.pdf'}/></label>;if(f.type==='checkbox')return <label className="check-field"><input type="checkbox" checked={!!value} onChange={e=>setValue(e.target.checked)}/><span>{f.label}</span></label>;if(f.type==='textarea')return <label><span>{f.label}</span><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder={f.placeholder||''}/></label>;if(f.type==='select')return <label><span>{f.label}</span><select value={value} onChange={e=>setValue(e.target.value)}>{f.options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></label>;return <label><span>{f.label}{f.type==='array'&&<small> · comma separated</small>}</span><input type={f.type==='number'?'number':f.type==='url'?'url':'text'} value={value} onChange={e=>setValue(e.target.value)} placeholder={f.placeholder||''}/></label>}
